#' Add and remove a rolling average
#'
#' @param x An [incidence2::incidence] object.
#' @param before how many prior dates to group with.
#' @param r Am object generated by [add_rolling_average].
#' @param ... Not currently used.
#'
#' @note If groups are present the average will be calculated across each
#' grouping, therefore care is required when plotting.
#'
#' @return
#'   - `rolling_average` An [incidence2::incidence] like object with an additional,
#'     averaged, column and class `incidence2_ra`.
#'   - `remove_rolling` An [incidence()] object.
#'
#' @examples
#' if (requireNamespace("outbreaks", quietly = TRUE) &&
#'     requireNamespace("incidence2", quietly = TRUE)) {
#'   data(ebola_sim_clean, package = "outbreaks")
#'   dat <- ebola_sim_clean$linelist
#'
#'   inci <- incidence2::incidence(dat,
#'                     date_index = date_of_onset,
#'                     interval = "week",
#'                     last_date = "2014-10-05",
#'                     groups = gender)
#'
#'   ra <- add_rolling_average(inci, before = 2)
#'   inci %>%
#'     incidence2::facet_plot(color = "white") %>%
#'     plot_rolling_average(ra)
#'
#'
#'   inci2 <- incidence2::regroup(inci)
#'   ra2 <- add_rolling_average(inci2, before = 2)
#'   inci2 %>%
#'     plot(color = "white") %>%
#'     plot_rolling_average(ra2)
#'
#' }
#'
#' @rdname rolling_average
#' @export
add_rolling_average <- function(x, ...) {
  UseMethod("add_rolling_average")
}

#' @rdname rolling_average
#' @aliases rolling_average.default
#' @export
add_rolling_average.default <- function(x, ...) {
  stop(sprintf("Not implemented for class %s",
               paste(class(x), collapse = ", ")))
}


#' @rdname rolling_average
#' @aliases rolling_average.incidence2
#' @export
add_rolling_average.incidence2 <- function(x, before = 2, ...) {
  ellipsis::check_dots_empty()
  group_vars <- incidence2::get_group_names(x)
  count_var <- incidence2::get_counts_name(x)

  if (!is.null(group_vars)) {
    out <- dplyr::group_by(x, dplyr::across( {{group_vars}} ))
  } else {
    out <- x
  }

  out <- dplyr::mutate(
    out,
    rolling_average = slider::slide_dbl(
      .data[[count_var]],
      mean,
      .before = before,
      .complete = TRUE))
  attributes(out) <- attributes(x)

  colnames(out)[length(out)] <- "rolling_average"
  attr(out, "rolling_average") <- "rolling_average"
  attr(out, "before") <- before
  class(out) <- c("incidence2_ra", class(out))
  out
}


#' @rdname rolling_average
#' @export
remove_rolling_average <- function(r) {
  ra <- attr(r, "rolling_average")
  r[[ra]] <- NULL
  attr(r, "rolling_average") <- NULL
  attr(r, "before") <- NULL
  class(r) <- class(r)[-(which(class(r) == "incidence2_ra"))]
  r
}
